language: c
compiler: gcc
dist: trusty

before_install:
    # add LLVM repository
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list
    - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    # clone NXDK repository
    - git clone https://github.com/xqemu/nxdk.git
    - cd nxdk
    - git submodule init && git submodule update --recursive

install:
    # install required packages
    - sudo apt-get install build-essential flex bison clang git clang-7 lldb-7 llvm-7 llvm-7-dev -y
    # create an alias for lld-link
    - alias lld-link=lld-link-7.0

script:
    # debug infos
    - uname -a
    - $CXX --version
    - pwd
    # try to compile
    - mkdir project
    - cd ..
    - pwd
    # TODO....
