language: c
compiler: gcc
dist: bionic
os: linux
notifications:
    email: false

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    
install:
    # install required packages
    - sudo apt-get install build-essential flex bison clang git clang-8 lldb-8 llvm-8 llvm-8-dev -y
    # create an alias for lld-link
    - alias lld-link=lld-link-8.0
    - alias clang=clang-8
    
before_script:
    # clone NXDK repository to /home/travis/build/Cxbx-Reloaded/
    - cd .. # because we currently are in /home/travis/build/Cxbx-Reloaded/xbox_kernel_test_suite
    - git clone https://github.com/XboxDev/nxdk.git
    - cd nxdk # now we are in /home/travis/build/Cxbx-Reloaded/nxdk
    - git submodule init && git submodule update --recursive
    - mkdir projects
    - cd projects # we are now in /home/travis/build/Cxbx-Reloaded/nxdk/projects/
    - mv ./../../xbox_kernel_test_suite ./ # move here the xbox_kernel_test_suite folder
    - cd xbox_kernel_test_suite # change current dir to /home/travis/build/Cxbx-Reloaded/nxdk/projects/xbox_kernel_test_suite

script:
    # debug infos
    - uname -a
    - pwd
    # build
    - make

before_deploy:
    - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "bin/default.xbe"
  overwrite: true
  skip_cleanup: true
