language: c
compiler: gcc
dist: trusty
os: linux
notifications:
    email: false

before_install:
    # add LLVM repository
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    
install:
    # install required packages
    - sudo apt-get install build-essential flex bison clang git clang-7 lldb-7 llvm-7 llvm-7-dev -y
    # create an alias for lld-link
    - alias lld-link=lld-link-7.0
    
before_script:
    # clone NXDK repository to /home/travis/build/Cxbx-Reloaded/
    - cd .. # because we currently are in /home/travis/build/Cxbx-Reloaded/xbox_kernel_test_suite
    - git clone https://github.com/xqemu/nxdk.git
    - cd nxdk # now we are in /home/travis/build/Cxbx-Reloaded/nxdk
    - git submodule init && git submodule update --recursive
    - mkdir projects
    - cd projects # we are now in /home/travis/build/Cxbx-Reloaded/nxdk/projects/
    - mv ./../../xbox_kernel_test_suite ./ # move here the xbox_kernel_test_suite folder
    - cd xbox_kernel_test_suite # change current dir to /home/travis/build/Cxbx-Reloaded/nxdk/projects/xbox_kernel_test_suite

script:
    # debug infos
    - uname -a
    - pwd
    # build
    - make

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
