#pragma once

#include "tests_av.h"
#include "tests_dbg.h"
#include "tests_ex.h"
#include "tests_fsc.h"
#include "tests_hal.h"
#include "tests_interlocked.h"
#include "tests_io.h"
#include "tests_iof.h"
#include "tests_kd.h"
#include "tests_ke.h"
#include "tests_kf.h"
#include "tests_ki.h"
#include "tests_mm.h"
#include "tests_nt.h"
#include "tests_ob.h"
#include "tests_obf.h"
#include "tests_obp.h"
#include "tests_phy.h"
#include "tests_ps.h"
#include "tests_rtl.h"
#include "tests_xbox.h"
#include "tests_xe.h"
#include "tests_xc.h"
#include "tests_irt.h"
#include "tests_xprofp.h"
#include "tests_unknown.h"
#include "tests_misc.h"

typedef struct {
    void (*func)(int func_num, const char* func_name);
    const char* name;
} kernel_api_test;

#define GEN_API_TEST(test_name) { .func = test_ ## test_name, .name = #test_name }

static kernel_api_test kernel_api_tests[] =
{
    GEN_API_TEST(panic),                                     // 0x0000 (0) NULL
    GEN_API_TEST(AvGetSavedDataAddress),                     // 0x0001 (1)
    GEN_API_TEST(AvSendTVEncoderOption),                     // 0x0002 (2)
    GEN_API_TEST(AvSetDisplayMode),                          // 0x0003 (3)
    GEN_API_TEST(AvSetSavedDataAddress),                     // 0x0004 (4)
    GEN_API_TEST(DbgBreakPoint),                             // 0x0005 (5)
    GEN_API_TEST(DbgBreakPointWithStatus),                   // 0x0006 (6)
    GEN_API_TEST(DbgLoadImageSymbols),                       // 0x0007 (7) DEVKIT
    GEN_API_TEST(DbgPrint),                                  // 0x0008 (8)
    GEN_API_TEST(HalReadSMCTrayState),                       // 0x0009 (9)
    GEN_API_TEST(DbgPrompt),                                 // 0x000A (10)
    GEN_API_TEST(DbgUnLoadImageSymbols),                     // 0x000B (11) DEVKIT
    GEN_API_TEST(ExAcquireReadWriteLockExclusive),           // 0x000C (12)
    GEN_API_TEST(ExAcquireReadWriteLockShared),              // 0x000D (13)
    GEN_API_TEST(ExAllocatePool),                            // 0x000E (14)
    GEN_API_TEST(ExAllocatePoolWithTag),                     // 0x000F (15)
    GEN_API_TEST(ExEventObjectType),                         // 0x0010 (16)
    GEN_API_TEST(ExFreePool),                                // 0x0011 (17)
    GEN_API_TEST(ExInitializeReadWriteLock),                 // 0x0012 (18)
    GEN_API_TEST(ExInterlockedAddLargeInteger),              // 0x0013 (19)
    GEN_API_TEST(ExInterlockedAddLargeStatistic),            // 0x0014 (20)
    GEN_API_TEST(ExInterlockedCompareExchange64),            // 0x0015 (21)
    GEN_API_TEST(ExMutantObjectType),                        // 0x0016 (22)
    GEN_API_TEST(ExQueryPoolBlockSize),                      // 0x0017 (23)
    GEN_API_TEST(ExQueryNonVolatileSetting),                 // 0x0018 (24)
    GEN_API_TEST(ExReadWriteRefurbInfo),                     // 0x0019 (25)
    GEN_API_TEST(ExRaiseException),                          // 0x001A (26)
    GEN_API_TEST(ExRaiseStatus),                             // 0x001B (27)
    GEN_API_TEST(ExReleaseReadWriteLock),                    // 0x001C (28)
    GEN_API_TEST(ExSaveNonVolatileSetting),                  // 0x001D (29)
    GEN_API_TEST(ExSemaphoreObjectType),                     // 0x001E (30)
    GEN_API_TEST(ExTimerObjectType),                         // 0x001F (31)
    GEN_API_TEST(ExfInterlockedInsertHeadList),              // 0x0020 (32)
    GEN_API_TEST(ExfInterlockedInsertTailList),              // 0x0021 (33)
    GEN_API_TEST(ExfInterlockedRemoveHeadList),              // 0x0022 (34)
    GEN_API_TEST(FscGetCacheSize),                           // 0x0023 (35)
    GEN_API_TEST(FscInvalidateIdleBlocks),                   // 0x0024 (36)
    GEN_API_TEST(FscSetCacheSize),                           // 0x0025 (37)
    GEN_API_TEST(HalClearSoftwareInterrupt),                 // 0x0026 (38)
    GEN_API_TEST(HalDisableSystemInterrupt),                 // 0x0027 (39)
    GEN_API_TEST(HalDiskCachePartitionCount),                // 0x0028 (40) A.k.a. "IdexDiskPartitionPrefixBuffer"
    GEN_API_TEST(HalDiskModelNumber),                        // 0x0029 (41)
    GEN_API_TEST(HalDiskSerialNumber),                       // 0x002A (42)
    GEN_API_TEST(HalEnableSystemInterrupt),                  // 0x002B (43)
    GEN_API_TEST(HalGetInterruptVector),                     // 0x002C (44)
    GEN_API_TEST(HalReadSMBusValue),                         // 0x002D (45)
    GEN_API_TEST(HalReadWritePCISpace),                      // 0x002E (46)
    GEN_API_TEST(HalRegisterShutdownNotification),           // 0x002F (47)
    GEN_API_TEST(HalRequestSoftwareInterrupt),               // 0x0030 (48)
    GEN_API_TEST(HalReturnToFirmware),                       // 0x0031 (49)
    GEN_API_TEST(HalWriteSMBusValue),                        // 0x0032 (50)
    GEN_API_TEST(InterlockedCompareExchange),                // 0x0033 (51)
    GEN_API_TEST(InterlockedDecrement),                      // 0x0034 (52)
    GEN_API_TEST(InterlockedIncrement),                      // 0x0035 (53)
    GEN_API_TEST(InterlockedExchange),                       // 0x0036 (54)
    GEN_API_TEST(InterlockedExchangeAdd),                    // 0x0037 (55)
    GEN_API_TEST(InterlockedFlushSList),                     // 0x0038 (56)
    GEN_API_TEST(InterlockedPopEntrySList),                  // 0x0039 (57)
    GEN_API_TEST(InterlockedPushEntrySList),                 // 0x003A (58)
    GEN_API_TEST(IoAllocateIrp),                             // 0x003B (59)
    GEN_API_TEST(IoBuildAsynchronousFsdRequest),             // 0x003C (60)
    GEN_API_TEST(IoBuildDeviceIoControlRequest),             // 0x003D (61)
    GEN_API_TEST(IoBuildSynchronousFsdRequest),              // 0x003E (62)
    GEN_API_TEST(IoCheckShareAccess),                        // 0x003F (63)
    GEN_API_TEST(IoCompletionObjectType),                    // 0x0040 (64)
    GEN_API_TEST(IoCreateDevice),                            // 0x0041 (65)
    GEN_API_TEST(IoCreateFile),                              // 0x0042 (66)
    GEN_API_TEST(IoCreateSymbolicLink),                      // 0x0043 (67)
    GEN_API_TEST(IoDeleteDevice),                            // 0x0044 (68)
    GEN_API_TEST(IoDeleteSymbolicLink),                      // 0x0045 (69)
    GEN_API_TEST(IoDeviceObjectType),                        // 0x0046 (70)
    GEN_API_TEST(IoFileObjectType),                          // 0x0047 (71)
    GEN_API_TEST(IoFreeIrp),                                 // 0x0048 (72)
    GEN_API_TEST(IoInitializeIrp),                           // 0x0049 (73)
    GEN_API_TEST(IoInvalidDeviceRequest),                    // 0x004A (74)
    GEN_API_TEST(IoQueryFileInformation),                    // 0x004B (75)
    GEN_API_TEST(IoQueryVolumeInformation),                  // 0x004C (76)
    GEN_API_TEST(IoQueueThreadIrp),                          // 0x004D (77)
    GEN_API_TEST(IoRemoveShareAccess),                       // 0x004E (78)
    GEN_API_TEST(IoSetIoCompletion),                         // 0x004F (79)
    GEN_API_TEST(IoSetShareAccess),                          // 0x0050 (80)
    GEN_API_TEST(IoStartNextPacket),                         // 0x0051 (81)
    GEN_API_TEST(IoStartNextPacketByKey),                    // 0x0052 (82)
    GEN_API_TEST(IoStartPacket),                             // 0x0053 (83)
    GEN_API_TEST(IoSynchronousDeviceIoControlRequest),       // 0x0054 (84)
    GEN_API_TEST(IoSynchronousFsdRequest),                   // 0x0055 (85)
    GEN_API_TEST(IofCallDriver),                             // 0x0056 (86)
    GEN_API_TEST(IofCompleteRequest),                        // 0x0057 (87)
    GEN_API_TEST(KdDebuggerEnabled),                         // 0x0058 (88)
    GEN_API_TEST(KdDebuggerNotPresent),                      // 0x0059 (89)
    GEN_API_TEST(IoDismountVolume),                          // 0x005A (90)
    GEN_API_TEST(IoDismountVolumeByName),                    // 0x005B (91)
    GEN_API_TEST(KeAlertResumeThread),                       // 0x005C (92)
    GEN_API_TEST(KeAlertThread),                             // 0x005D (93)
    GEN_API_TEST(KeBoostPriorityThread),                     // 0x005E (94)
    GEN_API_TEST(KeBugCheck),                                // 0x005F (95)
    GEN_API_TEST(KeBugCheckEx),                              // 0x0060 (96)
    GEN_API_TEST(KeCancelTimer),                             // 0x0061 (97)
    GEN_API_TEST(KeConnectInterrupt),                        // 0x0062 (98)
    GEN_API_TEST(KeDelayExecutionThread),                    // 0x0063 (99)
    GEN_API_TEST(KeDisconnectInterrupt),                     // 0x0064 (100)
    GEN_API_TEST(KeEnterCriticalRegion),                     // 0x0065 (101)
    GEN_API_TEST(MmGlobalData),                              // 0x0066 (102)
    GEN_API_TEST(KeGetCurrentIrql),                          // 0x0067 (103)
    GEN_API_TEST(KeGetCurrentThread),                        // 0x0068 (104)
    GEN_API_TEST(KeInitializeApc),                           // 0x0069 (105)
    GEN_API_TEST(KeInitializeDeviceQueue),                   // 0x006A (106)
    GEN_API_TEST(KeInitializeDpc),                           // 0x006B (107)
    GEN_API_TEST(KeInitializeEvent),                         // 0x006C (108)
    GEN_API_TEST(KeInitializeInterrupt),                     // 0x006D (109)
    GEN_API_TEST(KeInitializeMutant),                        // 0x006E (110)
    GEN_API_TEST(KeInitializeQueue),                         // 0x006F (111)
    GEN_API_TEST(KeInitializeSemaphore),                     // 0x0070 (112)
    GEN_API_TEST(KeInitializeTimerEx),                       // 0x0071 (113)
    GEN_API_TEST(KeInsertByKeyDeviceQueue),                  // 0x0072 (114)
    GEN_API_TEST(KeInsertDeviceQueue),                       // 0x0073 (115)
    GEN_API_TEST(KeInsertHeadQueue),                         // 0x0074 (116)
    GEN_API_TEST(KeInsertQueue),                             // 0x0075 (117)
    GEN_API_TEST(KeInsertQueueApc),                          // 0x0076 (118)
    GEN_API_TEST(KeInsertQueueDpc),                          // 0x0077 (119)
    GEN_API_TEST(KeInterruptTime),                           // 0x0078 (120) (Set by ConnectWindowsTimersToThunkTable)
    GEN_API_TEST(KeIsExecutingDpc),                          // 0x0079 (121)
    GEN_API_TEST(KeLeaveCriticalRegion),                     // 0x007A (122)
    GEN_API_TEST(KePulseEvent),                              // 0x007B (123)
    GEN_API_TEST(KeQueryBasePriorityThread),                 // 0x007C (124)
    GEN_API_TEST(KeQueryInterruptTime),                      // 0x007D (125)
    GEN_API_TEST(KeQueryPerformanceCounter),                 // 0x007E (126)
    GEN_API_TEST(KeQueryPerformanceFrequency),               // 0x007F (127)
    GEN_API_TEST(KeQuerySystemTime),                         // 0x0080 (128)
    GEN_API_TEST(KeRaiseIrqlToDpcLevel),                     // 0x0081 (129)
    GEN_API_TEST(KeRaiseIrqlToSynchLevel),                   // 0x0082 (130)
    GEN_API_TEST(KeReleaseMutant),                           // 0x0083 (131)
    GEN_API_TEST(KeReleaseSemaphore),                        // 0x0084 (132)
    GEN_API_TEST(KeRemoveByKeyDeviceQueue),                  // 0x0085 (133)
    GEN_API_TEST(KeRemoveDeviceQueue),                       // 0x0086 (134)
    GEN_API_TEST(KeRemoveEntryDeviceQueue),                  // 0x0087 (135)
    GEN_API_TEST(KeRemoveQueue),                             // 0x0088 (136)
    GEN_API_TEST(KeRemoveQueueDpc),                          // 0x0089 (137)
    GEN_API_TEST(KeResetEvent),                              // 0x008A (138)
    GEN_API_TEST(KeRestoreFloatingPointState),               // 0x008B (139)
    GEN_API_TEST(KeResumeThread),                            // 0x008C (140)
    GEN_API_TEST(KeRundownQueue),                            // 0x008D (141)
    GEN_API_TEST(KeSaveFloatingPointState),                  // 0x008E (142)
    GEN_API_TEST(KeSetBasePriorityThread),                   // 0x008F (143)
    GEN_API_TEST(KeSetDisableBoostThread),                   // 0x0090 (144)
    GEN_API_TEST(KeSetEvent),                                // 0x0091 (145)
    GEN_API_TEST(KeSetEventBoostPriority),                   // 0x0092 (146)
    GEN_API_TEST(KeSetPriorityProcess),                      // 0x0093 (147)
    GEN_API_TEST(KeSetPriorityThread),                       // 0x0094 (148)
    GEN_API_TEST(KeSetTimer),                                // 0x0095 (149)
    GEN_API_TEST(KeSetTimerEx),                              // 0x0096 (150)
    GEN_API_TEST(KeStallExecutionProcessor),                 // 0x0097 (151)
    GEN_API_TEST(KeSuspendThread),                           // 0x0098 (152)
    GEN_API_TEST(KeSynchronizeExecution),                    // 0x0099 (153)
    GEN_API_TEST(KeSystemTime),                              // 0x009A (154) (Set by ConnectWindowsTimersToThunkTable)
    GEN_API_TEST(KeTestAlertThread),                         // 0x009B (155)
    GEN_API_TEST(KeTickCount),                               // 0x009C (156)
    GEN_API_TEST(KeTimeIncrement),                           // 0x009D (157)
    GEN_API_TEST(KeWaitForMultipleObjects),                  // 0x009E (158)
    GEN_API_TEST(KeWaitForSingleObject),                     // 0x009F (159)
    GEN_API_TEST(KfRaiseIrql),                               // 0x00A0 (160)
    GEN_API_TEST(KfLowerIrql),                               // 0x00A1 (161)
    GEN_API_TEST(KiBugCheckData),                            // 0x00A2 (162)
    GEN_API_TEST(KiUnlockDispatcherDatabase),                // 0x00A3 (163)
    GEN_API_TEST(LaunchDataPage),                            // 0x00A4 (164)
    GEN_API_TEST(MmAllocateContiguousMemory),                // 0x00A5 (165)
    GEN_API_TEST(MmAllocateContiguousMemoryEx),              // 0x00A6 (166)
    GEN_API_TEST(MmAllocateSystemMemory),                    // 0x00A7 (167)
    GEN_API_TEST(MmClaimGpuInstanceMemory),                  // 0x00A8 (168)
    GEN_API_TEST(MmCreateKernelStack),                       // 0x00A9 (169)
    GEN_API_TEST(MmDeleteKernelStack),                       // 0x00AA (170)
    GEN_API_TEST(MmFreeContiguousMemory),                    // 0x00AB (171)
    GEN_API_TEST(MmFreeSystemMemory),                        // 0x00AC (172)
    GEN_API_TEST(MmGetPhysicalAddress),                      // 0x00AD (173)
    GEN_API_TEST(MmIsAddressValid),                          // 0x00AE (174)
    GEN_API_TEST(MmLockUnlockBufferPages),                   // 0x00AF (175)
    GEN_API_TEST(MmLockUnlockPhysicalPage),                  // 0x00B0 (176)
    GEN_API_TEST(MmMapIoSpace),                              // 0x00B1 (177)
    GEN_API_TEST(MmPersistContiguousMemory),                 // 0x00B2 (178)
    GEN_API_TEST(MmQueryAddressProtect),                     // 0x00B3 (179)
    GEN_API_TEST(MmQueryAllocationSize),                     // 0x00B4 (180)
    GEN_API_TEST(MmQueryStatistics),                         // 0x00B5 (181)
    GEN_API_TEST(MmSetAddressProtect),                       // 0x00B6 (182)
    GEN_API_TEST(MmUnmapIoSpace),                            // 0x00B7 (183)
    GEN_API_TEST(NtAllocateVirtualMemory),                   // 0x00B8 (184)
    GEN_API_TEST(NtCancelTimer),                             // 0x00B9 (185)
    GEN_API_TEST(NtClearEvent),                              // 0x00BA (186)
    GEN_API_TEST(NtClose),                                   // 0x00BB (187)
    GEN_API_TEST(NtCreateDirectoryObject),                   // 0x00BC (188)
    GEN_API_TEST(NtCreateEvent),                             // 0x00BD (189)
    GEN_API_TEST(NtCreateFile),                              // 0x00BE (190)
    GEN_API_TEST(NtCreateIoCompletion),                      // 0x00BF (191)
    GEN_API_TEST(NtCreateMutant),                            // 0x00C0 (192)
    GEN_API_TEST(NtCreateSemaphore),                         // 0x00C1 (193)
    GEN_API_TEST(NtCreateTimer),                             // 0x00C2 (194)
    GEN_API_TEST(NtDeleteFile),                              // 0x00C3 (195)
    GEN_API_TEST(NtDeviceIoControlFile),                     // 0x00C4 (196)
    GEN_API_TEST(NtDuplicateObject),                         // 0x00C5 (197)
    GEN_API_TEST(NtFlushBuffersFile),                        // 0x00C6 (198)
    GEN_API_TEST(NtFreeVirtualMemory),                       // 0x00C7 (199)
    GEN_API_TEST(NtFsControlFile),                           // 0x00C8 (200)
    GEN_API_TEST(NtOpenDirectoryObject),                     // 0x00C9 (201)
    GEN_API_TEST(NtOpenFile),                                // 0x00CA (202)
    GEN_API_TEST(NtOpenSymbolicLinkObject),                  // 0x00CB (203)
    GEN_API_TEST(NtProtectVirtualMemory),                    // 0x00CC (204)
    GEN_API_TEST(NtPulseEvent),                              // 0x00CD (205)
    GEN_API_TEST(NtQueryDirectoryFile),                      // 0x00CF (207)
    GEN_API_TEST(NtQueueApcThread),                          // 0x00CE (206)
    GEN_API_TEST(NtQueryDirectoryObject),                    // 0x00D0 (208)
    GEN_API_TEST(NtQueryEvent),                              // 0x00D1 (209)
    GEN_API_TEST(NtQueryFullAttributesFile),                 // 0x00D2 (210)
    GEN_API_TEST(NtQueryInformationFile),                    // 0x00D3 (211)
    GEN_API_TEST(NtQueryIoCompletion),                       // 0x00D4 (212)
    GEN_API_TEST(NtQueryMutant),                             // 0x00D5 (213)
    GEN_API_TEST(NtQuerySemaphore),                          // 0x00D6 (214)
    GEN_API_TEST(NtQuerySymbolicLinkObject),                 // 0x00D7 (215)
    GEN_API_TEST(NtQueryTimer),                              // 0x00D8 (216)
    GEN_API_TEST(NtQueryVirtualMemory),                      // 0x00D9 (217)
    GEN_API_TEST(NtQueryVolumeInformationFile),              // 0x00DA (218)
    GEN_API_TEST(NtReadFile),                                // 0x00DB (219)
    GEN_API_TEST(NtReadFileScatter),                         // 0x00DC (220)
    GEN_API_TEST(NtReleaseMutant),                           // 0x00DD (221)
    GEN_API_TEST(NtReleaseSemaphore),                        // 0x00DE (222)
    GEN_API_TEST(NtRemoveIoCompletion),                      // 0x00DF (223)
    GEN_API_TEST(NtResumeThread),                            // 0x00E0 (224)
    GEN_API_TEST(NtSetEvent),                                // 0x00E1 (225)
    GEN_API_TEST(NtSetInformationFile),                      // 0x00E2 (226)
    GEN_API_TEST(NtSetIoCompletion),                         // 0x00E3 (227)
    GEN_API_TEST(NtSetSystemTime),                           // 0x00E4 (228)
    GEN_API_TEST(NtSetTimerEx),                              // 0x00E5 (229)
    GEN_API_TEST(NtSignalAndWaitForSingleObjectEx),          // 0x00E6 (230)
    GEN_API_TEST(NtSuspendThread),                           // 0x00E7 (231)
    GEN_API_TEST(NtUserIoApcDispatcher),                     // 0x00E8 (232)
    GEN_API_TEST(NtWaitForSingleObject),                     // 0x00E9 (233)
    GEN_API_TEST(NtWaitForSingleObjectEx),                   // 0x00EA (234)
    GEN_API_TEST(NtWaitForMultipleObjectsEx),                // 0x00EB (235)
    GEN_API_TEST(NtWriteFile),                               // 0x00EC (236)
    GEN_API_TEST(NtWriteFileGather),                         // 0x00ED (237)
    GEN_API_TEST(NtYieldExecution),                          // 0x00EE (238)
    GEN_API_TEST(ObCreateObject),                            // 0x00EF (239)
    GEN_API_TEST(ObDirectoryObjectType),                     // 0x00F0 (240)
    GEN_API_TEST(ObInsertObject),                            // 0x00F1 (241)
    GEN_API_TEST(ObMakeTemporaryObject),                     // 0x00F2 (242)
    GEN_API_TEST(ObOpenObjectByName),                        // 0x00F3 (243)
    GEN_API_TEST(ObOpenObjectByPointer),                     // 0x00F4 (244)
    GEN_API_TEST(ObpObjectHandleTable),                      // 0x00F5 (245)
    GEN_API_TEST(ObReferenceObjectByHandle),                 // 0x00F6 (246)
    GEN_API_TEST(ObReferenceObjectByName),                   // 0x00F7 (247)
    GEN_API_TEST(ObReferenceObjectByPointer),                // 0x00F8 (248)
    GEN_API_TEST(ObSymbolicLinkObjectType),                  // 0x00F9 (249)
    GEN_API_TEST(ObfDereferenceObject),                      // 0x00FA (250)
    GEN_API_TEST(ObfReferenceObject),                        // 0x00FB (251)
    GEN_API_TEST(PhyGetLinkState),                           // 0x00FC (252)
    GEN_API_TEST(PhyInitialize),                             // 0x00FD (253)
    GEN_API_TEST(PsCreateSystemThread),                      // 0x00FE (254)
    GEN_API_TEST(PsCreateSystemThreadEx),                    // 0x00FF (255)
    GEN_API_TEST(PsQueryStatistics),                         // 0x0100 (256)
    GEN_API_TEST(PsSetCreateThreadNotifyRoutine),            // 0x0101 (257)
    GEN_API_TEST(PsTerminateSystemThread),                   // 0x0102 (258)
    GEN_API_TEST(PsThreadObjectType),                        // 0x0103 (259)
    GEN_API_TEST(RtlAnsiStringToUnicodeString),              // 0x0104 (260)
    GEN_API_TEST(RtlAppendStringToString),                   // 0x0105 (261)
    GEN_API_TEST(RtlAppendUnicodeStringToString),            // 0x0106 (262)
    GEN_API_TEST(RtlAppendUnicodeToString),                  // 0x0107 (263)
    GEN_API_TEST(RtlAssert),                                 // 0x0108 (264)
    GEN_API_TEST(RtlCaptureContext),                         // 0x0109 (265)
    GEN_API_TEST(RtlCaptureStackBackTrace),                  // 0x010A (266)
    GEN_API_TEST(RtlCharToInteger),                          // 0x010B (267)
    GEN_API_TEST(RtlCompareMemory),                          // 0x010C (268)
    GEN_API_TEST(RtlCompareMemoryUlong),                     // 0x010D (269)
    GEN_API_TEST(RtlCompareString),                          // 0x010E (270)
    GEN_API_TEST(RtlCompareUnicodeString),                   // 0x010F (271)
    GEN_API_TEST(RtlCopyString),                             // 0x0110 (272)
    GEN_API_TEST(RtlCopyUnicodeString),                      // 0x0111 (273)
    GEN_API_TEST(RtlCreateUnicodeString),                    // 0x0112 (274)
    GEN_API_TEST(RtlDowncaseUnicodeChar),                    // 0x0113 (275)
    GEN_API_TEST(RtlDowncaseUnicodeString),                  // 0x0114 (276)
    GEN_API_TEST(RtlEnterCriticalSection),                   // 0x0115 (277)
    GEN_API_TEST(RtlEnterCriticalSectionAndRegion),          // 0x0116 (278)
    GEN_API_TEST(RtlEqualString),                            // 0x0117 (279)
    GEN_API_TEST(RtlEqualUnicodeString),                     // 0x0118 (280)
    GEN_API_TEST(RtlExtendedIntegerMultiply),                // 0x0119 (281)
    GEN_API_TEST(RtlExtendedLargeIntegerDivide),             // 0x011A (282)
    GEN_API_TEST(RtlExtendedMagicDivide),                    // 0x011B (283)
    GEN_API_TEST(RtlFillMemory),                             // 0x011C (284)
    GEN_API_TEST(RtlFillMemoryUlong),                        // 0x011D (285)
    GEN_API_TEST(RtlFreeAnsiString),                         // 0x011E (286)
    GEN_API_TEST(RtlFreeUnicodeString),                      // 0x011F (287)
    GEN_API_TEST(RtlGetCallersAddress),                      // 0x0120 (288)
    GEN_API_TEST(RtlInitAnsiString),                         // 0x0121 (289)
    GEN_API_TEST(RtlInitUnicodeString),                      // 0x0122 (290)
    GEN_API_TEST(RtlInitializeCriticalSection),              // 0x0123 (291)
    GEN_API_TEST(RtlIntegerToChar),                          // 0x0124 (292)
    GEN_API_TEST(RtlIntegerToUnicodeString),                 // 0x0125 (293)
    GEN_API_TEST(RtlLeaveCriticalSection),                   // 0x0126 (294)
    GEN_API_TEST(RtlLeaveCriticalSectionAndRegion),          // 0x0127 (295)
    GEN_API_TEST(RtlLowerChar),                              // 0x0128 (296)
    GEN_API_TEST(RtlMapGenericMask),                         // 0x0129 (297)
    GEN_API_TEST(RtlMoveMemory),                             // 0x012A (298)
    GEN_API_TEST(RtlMultiByteToUnicodeN),                    // 0x012B (299)
    GEN_API_TEST(RtlMultiByteToUnicodeSize),                 // 0x012C (300)
    GEN_API_TEST(RtlNtStatusToDosError),                     // 0x012D (301)
    GEN_API_TEST(RtlRaiseException),                         // 0x012E (302)
    GEN_API_TEST(RtlRaiseStatus),                            // 0x012F (303)
    GEN_API_TEST(RtlTimeFieldsToTime),                       // 0x0130 (304)
    GEN_API_TEST(RtlTimeToTimeFields),                       // 0x0131 (305)
    GEN_API_TEST(RtlTryEnterCriticalSection),                // 0x0132 (306)
    GEN_API_TEST(RtlUlongByteSwap),                          // 0x0133 (307)
    GEN_API_TEST(RtlUnicodeStringToAnsiString),              // 0x0134 (308)
    GEN_API_TEST(RtlUnicodeStringToInteger),                 // 0x0135 (309)
    GEN_API_TEST(RtlUnicodeToMultiByteN),                    // 0x0136 (310)
    GEN_API_TEST(RtlUnicodeToMultiByteSize),                 // 0x0137 (311)
    GEN_API_TEST(RtlUnwind),                                 // 0x0138 (312)
    GEN_API_TEST(RtlUpcaseUnicodeChar),                      // 0x0139 (313)
    GEN_API_TEST(RtlUpcaseUnicodeString),                    // 0x013A (314)
    GEN_API_TEST(RtlUpcaseUnicodeToMultiByteN),              // 0x013B (315)
    GEN_API_TEST(RtlUpperChar),                              // 0x013C (316)
    GEN_API_TEST(RtlUpperString),                            // 0x013D (317)
    GEN_API_TEST(RtlUshortByteSwap),                         // 0x013E (318)
    GEN_API_TEST(RtlWalkFrameChain),                         // 0x013F (319)
    GEN_API_TEST(RtlZeroMemory),                             // 0x0140 (320)
    GEN_API_TEST(XboxEEPROMKey),                             // 0x0141 (321)
    GEN_API_TEST(XboxHardwareInfo),                          // 0x0142 (322)
    GEN_API_TEST(XboxHDKey),                                 // 0x0143 (323)
    GEN_API_TEST(XboxKrnlVersion),                           // 0x0144 (324)
    GEN_API_TEST(XboxSignatureKey),                          // 0x0145 (325)
    GEN_API_TEST(XeImageFileName),                           // 0x0146 (326)
    GEN_API_TEST(XeLoadSection),                             // 0x0147 (327)
    GEN_API_TEST(XeUnloadSection),                           // 0x0148 (328)
    GEN_API_TEST(READ_PORT_BUFFER_UCHAR),                    // 0x0149 (329)
    GEN_API_TEST(READ_PORT_BUFFER_USHORT),                   // 0x014A (330)
    GEN_API_TEST(READ_PORT_BUFFER_ULONG),                    // 0x014B (331)
    GEN_API_TEST(WRITE_PORT_BUFFER_UCHAR),                   // 0x014C (332)
    GEN_API_TEST(WRITE_PORT_BUFFER_USHORT),                  // 0x014D (333)
    GEN_API_TEST(WRITE_PORT_BUFFER_ULONG),                   // 0x014E (334)
    GEN_API_TEST(XcSHAInit),                                 // 0x014F (335)
    GEN_API_TEST(XcSHAUpdate),                               // 0x0150 (336)
    GEN_API_TEST(XcSHAFinal),                                // 0x0151 (337)
    GEN_API_TEST(XcRC4Key),                                  // 0x0152 (338)
    GEN_API_TEST(XcRC4Crypt),                                // 0x0153 (339)
    GEN_API_TEST(XcHMAC),                                    // 0x0154 (340)
    GEN_API_TEST(XcPKEncPublic),                             // 0x0155 (341)
    GEN_API_TEST(XcPKDecPrivate),                            // 0x0156 (342)
    GEN_API_TEST(XcPKGetKeyLen),                             // 0x0157 (343)
    GEN_API_TEST(XcVerifyPKCS1Signature),                    // 0x0158 (344)
    GEN_API_TEST(XcModExp),                                  // 0x0159 (345)
    GEN_API_TEST(XcDESKeyParity),                            // 0x015A (346)
    GEN_API_TEST(XcKeyTable),                                // 0x015B (347)
    GEN_API_TEST(XcBlockCrypt),                              // 0x015C (348)
    GEN_API_TEST(XcBlockCryptCBC),                           // 0x015D (349)
    GEN_API_TEST(XcCryptService),                            // 0x015E (350)
    GEN_API_TEST(XcUpdateCrypto),                            // 0x015F (351)
    GEN_API_TEST(RtlRip),                                    // 0x0160 (352)
    GEN_API_TEST(XboxLANKey),                                // 0x0161 (353)
    GEN_API_TEST(XboxAlternateSignatureKeys),                // 0x0162 (354)
    GEN_API_TEST(XePublicKeyData),                           // 0x0163 (355)
    GEN_API_TEST(HalBootSMCVideoMode),                       // 0x0164 (356)
    GEN_API_TEST(IdexChannelObject),                         // 0x0165 (357)
    GEN_API_TEST(HalIsResetOrShutdownPending),               // 0x0166 (358)
    GEN_API_TEST(IoMarkIrpMustComplete),                     // 0x0167 (359)
    GEN_API_TEST(HalInitiateShutdown),                       // 0x0168 (360)
    GEN_API_TEST(_snprintf),                                 // 0x0169 (361)
    GEN_API_TEST(_sprintf),                                  // 0x016A (362)
    GEN_API_TEST(_vsnprintf),                                // 0x016B (363)
    GEN_API_TEST(_vsprintf),                                 // 0x016C (364)
    GEN_API_TEST(HalEnableSecureTrayEject),                  // 0x016D (365)
    GEN_API_TEST(HalWriteSMCScratchRegister),                // 0x016E (366)
    GEN_API_TEST(UnknownAPI367),                             // 0x016F (367)
    GEN_API_TEST(UnknownAPI368),                             // 0x0170 (368)
    GEN_API_TEST(UnknownAPI369),                             // 0x0171 (369)
    GEN_API_TEST(XProfpControl),                             // 0x0172 (370) PROFILING
    GEN_API_TEST(XProfpGetData),                             // 0x0173 (371) PROFILING
    GEN_API_TEST(IrtClientInitFast),                         // 0x0174 (372) PROFILING
    GEN_API_TEST(IrtSweep),                                  // 0x0175 (373) PROFILING
    GEN_API_TEST(MmDbgAllocateMemory),                       // 0x0177 (374) DEVKIT
    GEN_API_TEST(MmDbgFreeMemory),                           // 0x0178 (375) DEVKIT - Returns number of pages released.
    GEN_API_TEST(MmDbgQueryAvailablePages),                  // 0x0179 (376) DEVKIT
    GEN_API_TEST(MmDbgReleaseAddress),                       // 0x017A (377) DEVKIT
    GEN_API_TEST(MmDbgWriteCheck),                           // 0x017A (378) DEVKIT
};

static const int kernel_api_tests_size = ARRAY_SIZE(kernel_api_tests);
