#pragma once

TEST_FUNC(panic);
TEST_FUNC(LaunchDataPage);
TEST_FUNC(READ_PORT_BUFFER_UCHAR);
TEST_FUNC(READ_PORT_BUFFER_USHORT);
TEST_FUNC(READ_PORT_BUFFER_ULONG);
TEST_FUNC(WRITE_PORT_BUFFER_UCHAR);
TEST_FUNC(WRITE_PORT_BUFFER_USHORT);
TEST_FUNC(WRITE_PORT_BUFFER_ULONG);
TEST_FUNC(IdexChannelObject);
TEST_FUNC(_snprintf);
TEST_FUNC(_sprintf);
TEST_FUNC(_vsnprintf);
TEST_FUNC(_vsprintf);
